### ISSUE TITLE
Failed to parse camera calibration

### ISSUE THREAD

**Issue by johaq** [iaslab-unipd/rgbd_calibration#10]
I used the sensor_data_collection to record some images. The camera info files look like this:
```
frame_id: xtion_rgb_optical_frame
height: 480
width: 640
distortion_model: plumb_bob
D: [0.0242488607686558, -0.101606204066611, 0.00729738654453138, 0.000871487597046265, 0]
K: [535.044041709227, 0, 319.05230353441, 0, 535.207054100367, 252.902906117044, 0, 0, 1]
R: [1, 0, 0, 0, 1, 0, 0, 0, 1]
P: [532.30517578125, 0, 319.043534864526, 0, 0, 533.854919433594, 254.863566213093, 0, 0, 0, 1, 0]
binning_x: 0
binning_y: 0
roi:
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
```
Trying to run the offline calibration gives the following error:
```
[ERROR] [1517587105.515380165]: Exception parsing YAML camera calibration:
yaml-cpp: error at line 0, column 0: bad conversion
[ERROR] [1517587105.515464671]: Failed to parse camera calibration from file [/home/johannes/pepper_depth/depth_camera_info.yaml]
```

Am I giving the wrong yaml file?
